<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Modules\Knowledge\Knowledge.Application\Knowledge.Application.csproj" />
    <ProjectReference Include="..\..\..\Shared\Shared.Application\Shared.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
  </ItemGroup>

</Project>
